- RCMRD_Demo/Demo_Crop_Growth.ipynb
Code changes:
Since the Sandbox is now default to Lab `pyplot` is not supported for JupyterLab 
Change `%pyplot notebook% to plot the images using `%matplotlib inline` 
Note that this can also be used with notebook and Lab.
In order to have an interactive inline we need to set the `%matplotlib inline` to `%matplotlib widget`
> Change pyplot extentions to plot using matplotlib inline

- Scripts/deafrica_dask.py
Added a `display_client` param to the Africa dask function that was added to the DEA version. Allows users to hide the client info if required.
> Add display_client param to dask code

- Scripts/deafrica_plotting.py
Issue #54 was caused by DEAfrica S1 data loading with an unexpected dimension order, which caused time to be used instead of longitude when calculating the image aspect in `rgb`.
Have replaced the existing code with `from odc.ui import image_aspect` which is more resilient to dimension order.
- Closes Issue #54
> Close #54 by calculating aspect using `odc.ui` tools

- Frequently_used_code/Rasterize_vectorize.ipynb
Updated minor issues with notebook. Includes removal of "scripts" folder reference from links to deafrica_spatialtools.py. Description section was converted from paragraph of text to list of dot points for clarity and consistency. Updated Note to **Note** to conform to other notebooks.
> Update Rasterize and Vectorize notebook

- Scripts/deafrica_datahandling.py
Adds examples for making composites using `first` and `last`
> Add first and last composite examples

- Scripts/deafrica_datahandling.py
The masking module has moved. Updating it to avoid the warning:
```
/env/lib/python3.6/site-packages/datacube/storage/masking.py:4: DeprecationWarning: datacube.storage.masking has moved to datacube.utils.masking
category=DeprecationWarning)
```
> Import masking from new location

- Beginners_guide/README.md
Reported here https://github.com/GeoscienceAustralia/dea-sandbox/issues/89
fix minor typo
> Fix typo in readme

- Scripts/deafrica_plotting.py
Computes dask arrays before plotting to prevent multiple evaluations within function
- Closes Issue #141
> Compute before plotting

- Real_world_examples/Coastal_erosion.ipynb
The coastal erosion notebook had a setting to use collection 2 data, which is not available in the public sandbox. This change fixes this to use collection 1 data.
> Change from using C2 to C1 data

- Scripts/deafrica_dask.py
Allow additional kwargs to be passed to create_local_dask_cluster(), e.g. n_workers.
> Allow additional kwargs in create_local_dask_cluster().

- Tools/setup.py
Make sure `deafrica-tools` installing `geopandas == 0.9.0` as part of `dea-sandbox` image upgrade
> update geopanda dependency

- Tools/deafrica_tools/datahandling.py
The `deafrica_tools.load_ard` func currently has a bug where setting `ls7_slc_off=False` or `ls7_slc_off=True` has no effect. This is because an older product name was used instead of `ls7_sr`.
> Fix Landsat SLC-off bug

- Real_world_examples/Wetlands_insight_tool.ipynb
- Tools/deafrica_tools/app/wetlandsinsighttool.py
- Tools/deafrica_tools/app/widgetconstructors.py
- Change basemap in app to CartoDB Positron
- Add ESRI basemap as overlay option
- Turn on zoom with mouse on map
> Update overlay layers to include ESRI basemap

- Tools/deafrica_tools/datahandling.py
Also snuck into the PR the removal of an import in the `deafrica-tools.datahandling` script that was causing a warning
> update mangroves analysis to use indexed GMW

- Datasets/GeoMAD.ipynb
- Tools/deafrica_tools/app/geomedian.py
- Tools/setup.py
Geomedian widget migrated from defunct training website to the Datasets notebook. Interactive app added to the Tools package.
> Added geomedian widget to Tools and Datasets.

- Tools/deafrica_tools/datahandling.py
Update load_ard to include ls9 and remove bug when only loading pq band
- Closes Issue #348 
- Closes Issue #339
> ls9 load_ard and pq bug

- Tools/deafrica_tools/areaofinterest.py
- Tools/index.rst
- Updated the names in the areaofinterest function to moce away from using shapefile and rather use the term vector to include both ESRI shapefile and geojson.
- Added the reference guide for  areaofinterest function to "DE Africa Tools Package"
> Add reference guide for areaofinterest function

- Tools/deafrica_tools/areaofinterest.py
- Tools/index.rst
Changing shapefile_path to vector_path affects all the notebooks that use the function. To avoid updating all the notebooks, which may cause issues with the coming upgrades, reverting back to using shapefile_path.
> Revert "Add reference guide for areaofinterest function"

- Tools/deafrica_tools/coastal.py
- Tools/pyproject.toml
- Update the `coastal` module to use the correct `pyTMD` namespaces and functions
> Fix coastal erosion notebook

- Tools/README.md
- Tools/deafrica_tools/__init__.py
- Tools/pyproject.toml
Changes correct the installation docs to ensure the latest version of deafrica-tools is installed on the sandbox with pip. Correct version tagging has also been added to the project. 
> Fix deafrica_tools docs and add version for pip install

- Tools/deafrica_tools/__init__.py
- Tools/deafrica_tools/areaofinterest.py
- Tools/deafrica_tools/bandindices.py
- Tools/deafrica_tools/classification.py
- Tools/deafrica_tools/coastal.py
- Tools/deafrica_tools/dask.py
- Tools/pyproject.toml
- Update coastal module to match updates to pyTMD >= 2.1.5
- Lint the areaofinterest, bandindices and classification modules
> Update coastal module

- Tools/deafrica_tools/__init__.py
- Tools/deafrica_tools/coastal.py
- Tools/pyproject.toml
> Set crop parameter default to False
