digitalearthafrica/deafrica-sandbox-notebooks

Frequently_used_code/Rasterize_vectorize.ipynb, Scripts/deafrica_spatialtools.py
Two new functions to add to `deafrica_spatialtools.py` that make it significantly easier to convert between xarray and geopandas objects.
=> new xarray rasterizing and vectorizing functions + notebook demonstration

Scripts/deafrica_dask.py
A new python script to sit in Scripts/ that will simplify the creation of a local dask cluster.
=> deafrica-dask python script

Scripts/deafrica_bandindices.py
=> bug fix in calc_indices

Scripts/deafrica_datahandling.py
- closes issue #53 
odc.algo has now been updated on the Sandbox so removing the required functions from deafrica_datahandling
=> remove odc-tools funcs from deafrica_datahandling

Scripts/deafrica_classificationtools.py, Scripts/deafrica_dask.py, Scripts/deafrica_datahandling.py
- `deafrica_datahandling.mostcommon_crs`: removed redundant line of code
- `deafrica_classificationtools.get_training_from_shape`: various tweaks, including suppressing unwanted print statements from embedded functions, and adding option for 'std dev' data reduction.
- `deafrica_dask.create_local_dask_cluster`: add option to assign `aws_unsigned` to either True or False (cannot load C2 data if hard-coded to True).
=> various minor updates to scripts

Scripts/deafrica_spatialtools.py
Fixes the following issues:
https://github.com/GeoscienceAustralia/dea-notebooks/issues/539
https://github.com/GeoscienceAustralia/dea-notebooks/issues/536
=> Update subpixel_contours to fix recent bugs and add references

Frequently_used_code/Working_with_time.ipynb
Added background section. Broke up "Indexing by time" section and formatted headings as a result.
- [ x Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
=> Update Working with time notebook

Scripts/deafrica_classificationtools.py
Added a PCA notebook and fixed a bug in the classifications script.
=> Added a PCA notebook.

Beginners_guide/08_Parallel_processing_with_dask.ipynb
Very minor update after renaming of notebooks
=> Fix hyperlinks to images in Dask notebook

Real_world_examples/Urban_change_detection.ipynb
Removing reference to Sentinel-2 in the markdown #178
=> remove reference to s2

.github/workflows/blank.yml
Calls webhook on RTD API v3 for deafrica-docs
=> Add Github Action to trigger RTD build

Beginners_guide/08_Parallel_processing_with_dask.ipynb, Frequently_used_code/Generating_geomedian_composites.ipynb, Frequently_used_code/Monitoring_water_quality.ipynb, Frequently_used_code/Tidal_modelling.ipynb, Frequently_used_code/Urban_index_comparison.ipynb, Real_world_examples/Change_filmstrips.ipynb, Real_world_examples/Chlorophyll_monitoring.ipynb, Real_world_examples/Coastal_erosion.ipynb, Real_world_examples/Intertidal_elevation.ipynb, Real_world_examples/Mangrove_analysis.ipynb, Real_world_examples/Urban_change_detection.ipynb
Replaces the user name in the dask dashboard link to `sandbox_user`, and invalidates the link
=> Remove usernames and links from dask dashboard

.gitignore, Tools/deafrica_tools/dask.py
For some of our internal users, we are experimenting with scalable dask-gateway clusters.
No notebooks are changed by this.
=> implement create_dask_gateway_cluster function

Tools/deafrica_tools/dask.py
=> friendly error message for unauthorized dask gateway access

Frequently_used_code/Spectral_temporal_widget.ipynb
=> Updated title for spectral-temporal notebook

Frequently_used_code/Spectral_temporal_widget.ipynb
=>  add contributors

Scripts/notebookapp_spectraltemporal.py
=> Odc wetland widget

Frequently_used_code/Spectral_temporal_widget_tcw.ipynb
-add second notebook for a different index. this is so you can play with the nice NDVI one, and break the less nice TCW one.
=> notes for handover

Frequently_used_code/Spectral_temporal_widget_tcw.ipynb
=> Changes to notebook to include updated to-do list

odc-waterbodies.ipynb
=> including s2 into waterbodies notebook

Use_cases/Surface_mining_screening/Surface_mining_screening.py
=> updated the python code

Datasets/Fractional_Cover.ipynb
=> fix location description

.github/workflows/trigger_docs_build.yml
Trigger the RTD docs.digitalearthafrica.org to build when `main` branch is updated
=> Trigger RTD build on main branch

.github/pull_request_template.md, DEAfrica_notebooks_template.ipynb
Updates PR template and notebook template to include colour scheme considerations.
=> Added colour scheme criterion.

Datasets/Landcover_Classification.ipynb
=> Add a note about class lists in LC notebook

Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb
Fix scipy import for crop mask notebook
- Closes Issue #369
=> Fix import for ML notebook

SDGs/index.rst
Added the index.rst file to the SDGs folder
- [ x] Remove any unused/empty code cells
- [ x] Remove any guidance cells (e.g. `General advice`)
- [ x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [ x] Include relevant tags in the first notebook cell and re-use tags if possible
- [ x] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with …
=> SDGs indicators

Tools/deafrica_tools/load_isda.py
Add 2 files:
- Datasets notebook demonstrating loading iSDA soil data
- Python script containing loading wrapper, similar to load_era5()
- Closes Issue #396
=> add soil nb and tools

Datasets/Coastlines.ipynb
Fix links to coastlines docs page in the coastlines notebook.
=> Add coastlines docs link

Beginners_guide/05_Basic_analysis.ipynb
#433 
- [x ] Remove any unused Python packages from `Load packages`
- [ x] Remove any unused/empty code cells
- [ x] Remove any guidance cells (e.g. `General advice`)
- [x ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [ x] Include relevant tags in the first notebook cell and re-use tags if possible
- [ x] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or …
=> Update 05 Basic analysis

DEAfricaInfo.ipynb
A template page for DE Africa Information.
=> Template for Information page

Tools/pyproject.toml
Update  pyproject.toml file version to 2.0.2
=> pyproject.toml version 2.0.2

.github/workflows/publish.yml
=> Add target directory of dist/ for publishing workflow

Tools/pyproject.toml
=> force pyTMD version > 2.7

Tools/pyproject.toml
Update deafrica-tool version to 2.3.3 for fix failed workflow https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/actions/runs/7707522526
=> Update deafrica-tool version to 2.3.3

Tools/deafrica_tools/__init__.py, Tools/pyproject.toml
=> update deafrica-tools to 2.3.8

.github/workflows/download_terms.yaml, .github/workflows/upload_terms.yaml
=> Disable translation workflows

Tools/deafrica_tools/__init__.py, Tools/index.rst, Tools/pyproject.toml
=> updated tools

README.md
Update the DE Africa notebooks citation in the README.
=> new citation

Frequently_used_code/Working_with_time.ipynb, Real_world_examples/Animation_with_rainfall.ipynb
Updated `Animation_with_rainfall` and `Working_with_time` notebook with guidelines from https://www.tarantool.io/en/doc/2.11/contributing/docs/sphinx-warnings/ to check if the warning can be avoided and move to the next notebook.
=> update two notebooks

Supplementary_data/Endnote/Endnote.md
=> minor changes

Tools/index.rst
=> update index v1

Tools/deafrica_tools/__init__.py, Tools/deafrica_tools/waterbodies.py, Tools/pyproject.toml
Add function to plot waterbodies colored by the `last_valid_obs` column.
=> Add function to plot waterbodies colored by the `last_valid_obs` column.

Tools/deafrica_tools/__init__.py, Tools/pyproject.toml
=> Remove upper bounds for python version requirement

Real_world_examples/Urban_green_space.ipynb, Tools/deafrica_tools/__init__.py
=> Africapolis

Tools/pyproject.toml
=> update to version to 2.5.7

Use_cases/Limpopo_River_Basin/01_Dam_Volume_Prediction/01_dam_volume_data_preprocessing.ipynb, Use_cases/Limpopo_River_Basin/01_Dam_Volume_Prediction/02_dam_volume_model_training.ipynb, Use_cases/Limpopo_River_Basin/01_Dam_Volume_Prediction/03_dam_volume_ model_prediction.ipynb
=> reference updates

Tools/deafrica_tools/__init__.py, Tools/deafrica_tools/load_soil_moisture.py
Replace the Deprecated NCI THREDDS Server with the new one
https://thredds.nci.org.au/thredds/catalog/catalog.html
=> Update product baseurl

Tools/deafrica_tools/__init__.py, Tools/deafrica_tools/load_soil_moisture.py
Reverts digitalearthafrica/deafrica-sandbox-notebooks#597
=> Revert "Update product baseurl"
